### ISSUE TITLE
http-inst-in  No description for Checkbox

### ISSUE THREAD

**Issue by Landsailor** [bmdevx/node-red-contrib-http-instance#1]
There is no visible description for the checkbox here:
<img width="517" alt="Screen Shot 2023-02-20 at 8 41 16 AM" src="https://user-images.githubusercontent.com/1393119/220161846-a8160b94-7db0-4cc1-936f-e62111dbb7a2.png">

It should likely display "Accept file uploads?"
From https://github.com/bmdevx/node-red-contrib-http-instance/blob/master/nodes/node-in-out.html

`    <div class="form-row form-row-http-in-upload hide">
        <label>&nbsp;</label>
        <input type="checkbox" id="node-input-upload" style="display: inline-block; width: auto; vertical-align: top;">
        <label for="node-input-upload" style="width: 70%;" data-i18n="httpin.label.upload"></label>
    </div>`

**Comment by bmdevx** [comment]
Should be fixed now with release 1.0.2
